WIP isolate execution

diff --git a/garlic/stages/launcher/run b/garlic/stages/launcher/run
--- a/garlic/stages/launcher/run
+++ b/garlic/stages/launcher/run
@@ -1,10 +1,9 @@
 #!/bin/sh -ex
 
->&2 echo "Running launcher run stage"
-env
+>&2 echo "Running launcher"
 
-if [ -e /nix ]; then
-  >&2 echo "Cannot use the launcher inside nix environment!"
+if [ ! -e "/nix" ]; then
+  >&2 echo "missing /nix"
   exit 1
 fi
 
@@ -12,8 +11,10 @@ if [ -z "$GARLIC_OUT" ]; then
   >&2 echo "GARLIC_OUT is not set"
   exit 1
 fi
-  
+
 mkdir -p "$GARLIC_OUT"
 cd "$GARLIC_OUT"
 
-exec nix-isolate @nixPrefix@@out@/bin/stage2
+for j in @out@/apps/*; do
+  $j/bin/run
+done
